### ISSUE TITLE
Lesson 9. Task 2. Car

### ISSUE THREAD

**Issue by milkina** [petrykin/homeworks#1]
Добавьте в Car.toString вывод инфо о водителе и двигателе.

**Comment by petrykin** [comment]
Сделано в #75b4a9a66b69efaa0ea164b2bc86f1cc11ee0f75

**Comment by petrykin** [comment]
Fixes [#75b4a9a66b69efaa0ea164b2bc86f1cc11ee0f75](url)

**Comment by petrykin** [comment]
Done
