### ISSUE TITLE
Lesson 13. Task 3.Обобщенный класс MinMax

### ISSUE THREAD

**Issue by milkina** [petrykin/homeworks#6]
1. Вы объявили переменную private NumberFormat nf;, но негде ее не используете.

**Comment by petrykin** [comment]
хотел использовать NumberFormat, а потом передумал, но удалить забыл )))

**Comment by milkina** [comment]
Еще (пропустила) - интерфейс Comparable тоже обобщенный, поэтому лучше писать так:
public class MinMax<T extends Comparable<T>>
